const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing');
const fs=require('fs');
const {doc,setDoc,getDoc,updateDoc,deleteDoc,collection,getDocs}=require('firebase/firestore');
let n=0,bad=0;
const t=async(name,p)=>{try{await p;n++;console.log('ok -',name)}catch(e){bad++;console.log('FAIL -',name,String(e.message).slice(0,200))}};
(async()=>{
const env=await initializeTestEnvironment({projectId:'demo-pl',firestore:{rules:fs.readFileSync(__dirname+'/../firestore.rules','utf8'),host:'127.0.0.1',port:8089}});
const ctx=(uid,email,verified=true)=>env.authenticatedContext(uid,{email,email_verified:verified}).firestore();
const A=ctx('a','a@x.com'),B=ctx('b','b@x.com'),C=ctx('c','c@x.com'),anon=env.unauthenticatedContext().firestore(),AU=ctx('a2','a2@x.com',false);
const course=(extra={})=>({name:'GATE DA',ownerUid:'a',members:[],plan:{subjects:[],blocks:[]},...extra});
const sess=(uid,over={})=>({uid,s:1000,e:2000000,device:'phone-1',source:'phone',...over});
await t('owner creates a course',assertSucceeds(setDoc(doc(A,'courses/c1'),course())));
await t('cannot create a course owned by someone else',assertFails(setDoc(doc(B,'courses/c2'),course())));
await t('anonymous cannot read',assertFails(getDoc(doc(anon,'courses/c1'))));
await t('unverified email cannot read own course',assertFails(getDoc(doc(AU,'courses/c1'))));
await t('stranger cannot read the course',assertFails(getDoc(doc(B,'courses/c1'))));
await t('owner reads the course',assertSucceeds(getDoc(doc(A,'courses/c1'))));
await t('course with unknown field is rejected',assertFails(setDoc(doc(A,'courses/c3'),course({evil:1}))));
await t('course with 400 blocks is rejected',assertFails(setDoc(doc(A,'courses/c4'),course({plan:{subjects:[],blocks:new Array(400).fill({})}}))));
await t('owner writes own session',assertSucceeds(setDoc(doc(A,'courses/c1/people/a/sessions/s1'),sess('a'))));
await t('owner cannot write a session as another uid',assertFails(setDoc(doc(A,'courses/c1/people/b/sessions/s1'),sess('b'))));
await t('session over 12 hours is rejected',assertFails(setDoc(doc(A,'courses/c1/people/a/sessions/s2'),sess('a',{e:1000+50000000}))));
await t('session with bad source is rejected',assertFails(setDoc(doc(A,'courses/c1/people/a/sessions/s3'),sess('a',{source:'bot'}))));
await t('session end before start is rejected',assertFails(setDoc(doc(A,'courses/c1/people/a/sessions/s4'),sess('a',{s:5,e:3}))));
await t('stranger cannot read sessions',assertFails(getDocs(collection(B,'courses/c1/people/a/sessions'))));
await t('owner invites by email',assertSucceeds(updateDoc(doc(A,'courses/c1'),{invited:['b@x.com']})));
await t('invited person joins themselves',assertSucceeds(updateDoc(doc(B,'courses/c1'),{members:['b']})));
await t('invited person cannot change the plan',assertFails(updateDoc(doc(B,'courses/c1'),{plan:{subjects:[],blocks:[],x:1}})));
await t('member can read the owner sessions (combined view)',assertSucceeds(getDocs(collection(B,'courses/c1/people/a/sessions'))));
await t('member writes own session',assertSucceeds(setDoc(doc(B,'courses/c1/people/b/sessions/s1'),sess('b'))));
await t('member cannot edit the owner session',assertFails(updateDoc(doc(B,'courses/c1/people/a/sessions/s1'),{e:3000})));
await t('member cannot delete the owner session',assertFails(deleteDoc(doc(B,'courses/c1/people/a/sessions/s1'))));
await t('member cannot add someone else to members',assertFails(updateDoc(doc(B,'courses/c1'),{members:['b','c']})));
await t('uninvited person cannot join',assertFails(updateDoc(doc(C,'courses/c1'),{members:['b','c']})));
await t('owner materials are private from members',assertSucceeds(setDoc(doc(A,'courses/c1/people/a/materials/m1'),{title:'PRML',kind:'theory',total:700,done:10})));
await t('member cannot read owner materials',assertFails(getDoc(doc(B,'courses/c1/people/a/materials/m1'))));
await t('material with negative progress is rejected',assertFails(setDoc(doc(A,'courses/c1/people/a/materials/m2'),{title:'x',kind:'theory',total:10,done:-1})));
await t('usage stores intervals only',assertSucceeds(setDoc(doc(A,'courses/c1/people/a/usage/phone-1_2026-10-05'),{uid:'a',device:'phone-1',day:'2026-10-05',intervals:[[1,2]]})));
await t('usage with extra app-name field is rejected',assertFails(setDoc(doc(A,'courses/c1/people/a/usage/phone-1_2026-10-06'),{uid:'a',device:'phone-1',day:'2026-10-06',intervals:[],apps:['com.x']})));
await t('random collection is closed',assertFails(setDoc(doc(A,'other/x'),{a:1})));
await t('owner deletes the course',assertSucceeds(deleteDoc(doc(A,'courses/c1'))));
console.log(n+' passed, '+bad+' failed');
await env.cleanup();process.exit(bad?1:0);
})().catch(e=>{console.log('ERR',e.message);process.exit(2)});
